s

diff --git a/.local/bin/monitors b/.local/bin/monitors
--- a/.local/bin/monitors
+++ b/.local/bin/monitors
@@ -1,5 +1,9 @@
 #!/bin/sh
 
+if xrandr --listproviders 2>/dev/null | grep -q NVIDIA; then
+  xrandr --setprovideroutputsource modesetting NVIDIA-0 || echo "Failed to set NVIDIA provider"
+fi
+
 for output in $(xrandr | grep " connected" | awk '{print $1}'); do
   xrandr --output "$output" --mode 1920x1080 --rate 60.00 2>/dev/null
 done
